HOST CLS

set lines 80
set serveroutput on size 200000
set veri off
set feed off
set pages 0
set long 32000

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY OFF
SET TERM ON
SET WRAP ON

set pagesize 0
Col p1 format a120

SPOOL &3;
PROMPT Registro de Instalación
SELECT 'Fecha: '||TO_CHAR(sysdate,'DD/MM/YYYY HH24:MI') FROM DUAL;
SELECT 'Lugar: '||contenido FROM config WHERE nombre_parametro='MUNICIPALIDAD';
PROMPT Versión Act: [EjecutarScript];
PROMPT Instancia  : [&1];
PROMPT RafamVer   : [&2];
PROMPT ----------------------------------------------------------;

SPOOL off;



PROMPT CREANDO INDICES FOREING KEY, ESPERE, ESTA OPERACION PUEDE TARDAR ALGUNOS MINUTOS;

CREATE TABLE OWNER_RAFAM.CAI_INDICES_FK AS 
SELECT REEMPLAZAR_NOMLARGOSxPREF(U12.CONSTRAINT_NAME || '_IA') AS contraint_name, 
       U12.TABLE_NAME as table_name,
       U12.COLUMN_NAME_1 as col_1, 
       U12.COLUMN_NAME_2 as col_2,
       U3456.COLUMN_NAME_3 as col_3,
       U3456.COLUMN_NAME_4 as col_4,
       U3456.COLUMN_NAME_5 as col_5,
       U3456.COLUMN_NAME_6 as col_6       
FROM 
(
SELECT U34.CONSTRAINT_NAME,
       U34.TABLE_NAME,       
       U34.COLUMN_NAME_3,
       U34.COLUMN_NAME_4,
       U56.COLUMN_NAME_5,
       U56.COLUMN_NAME_6 
FROM 
 (
SELECT U5.CONSTRAINT_NAME,U5.TABLE_NAME,U5.COLUMN_NAME COLUMN_NAME_5,U6.COLUMN_NAME COLUMN_NAME_6 FROM 
  (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
    (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R'
    ) 
    UC,
    (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
     FROM USER_CONS_COLUMNS
     WHERE POSITION=6
    ) UCC
    WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME        
  ) U6,
  (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
    (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R') 
    UC,
    (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
     FROM USER_CONS_COLUMNS
     WHERE POSITION=5
    ) UCC
    WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME
  )        
  U5
  WHERE U6.CONSTRAINT_NAME(+)=U5.CONSTRAINT_NAME
 ) U56,
 (
 SELECT U3.CONSTRAINT_NAME,U3.TABLE_NAME,U3.COLUMN_NAME COLUMN_NAME_3,U4.COLUMN_NAME  COLUMN_NAME_4 FROM 
  (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
    (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R'
    ) 
    UC,
    (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
     FROM USER_CONS_COLUMNS
     WHERE POSITION=4
    ) UCC
    WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME        
  ) U4,
  (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
    (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R') 
    UC,
    (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
     FROM USER_CONS_COLUMNS
     WHERE POSITION=3
    ) UCC
    WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME
  )        
  U3
  WHERE U4.CONSTRAINT_NAME(+)=U3.CONSTRAINT_NAME
 ) U34
 WHERE U56.CONSTRAINT_NAME(+)=U34.CONSTRAINT_NAME
) U3456,
(
 SELECT U1.CONSTRAINT_NAME,U1.TABLE_NAME,U1.COLUMN_NAME COLUMN_NAME_1,U2.COLUMN_NAME  COLUMN_NAME_2 FROM 
 (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
   (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R'
   ) 
   UC,
   (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
    FROM USER_CONS_COLUMNS
    WHERE POSITION=2
   ) UCC
   WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME        
 ) U2,
 (SELECT UCC.CONSTRAINT_NAME,UCC.TABLE_NAME,UCC.COLUMN_NAME FROM 
   (SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS 
       WHERE CONSTRAINT_TYPE='R'
   ) 
   UC,
   (SELECT CONSTRAINT_NAME,TABLE_NAME,COLUMN_NAME,POSITION 
    FROM USER_CONS_COLUMNS
    WHERE POSITION=1
   ) UCC
   WHERE UC.CONSTRAINT_NAME=UCC.CONSTRAINT_NAME
 )        
 U1
 WHERE U2.CONSTRAINT_NAME(+)=U1.CONSTRAINT_NAME
) U12
WHERE U3456.CONSTRAINT_NAME(+)=U12.CONSTRAINT_NAME;


--Borra los indices existentes
DELETE OWNER_RAFAM.CAI_INDICES_FK c 
where  EXISTS 
(SELECT '1' FROM user_indexes WHERE index_name=c.contraint_name);

COMMIT;

SPOOL &2\SCRIPTS\crear_indices_fk.log;
PROMPT ------------------CREANDO ARCHIVO DE INDICES ------------------;
SELECT 'PROMPT CREANDO ' || CONTRAINT_NAME || ';' || CHR(10) || 'CREATE INDEX ' || CONTRAINT_NAME || ' ON ' || chr(10) ||
       TABLE_NAME || ' (' ||
       COL_1 || 
       DECODE(COL_2,'','',','||COL_2) ||
       DECODE(COL_3,'','',','||COL_3) ||
       DECODE(COL_4,'','',','||COL_4) ||
       DECODE(COL_5,'','',','||COL_5) ||
       DECODE(COL_6,'','',','||COL_6) ||
       ')'|| chr(10) ||
       ' PCTFREE  10'|| chr(10) ||
       ' TABLESPACE INDICES;'||CHR(10) p1
FROM CAI_INDICES_FK
WHERE NOT EXISTS (SELECT INDEX_NAME FROM USER_INDEXES WHERE INDEX_NAME=CONTRAINT_NAME); 

SPOOL OFF;

PROMPT ELIMINANDO TABLA TEMPORARIA;
--DROP TABLE OWNER_RAFAM.CAI_INDICES_FK;

PROMPT CREANDO INDICES;

SPOOL &2\SCRIPTS\ejecucion_crear_indices_fk.log;
PROMPT ------------------EJECUTANDO ARCHIVO DE CREACION DE INDICES ------------------;
start &2\SCRIPTS\crear_indices_fk.log;

SPOOL OFF;

PROMPT -----------------------------FIN------------------;

SPOOL OFF;

EXIT;
