HOST CLS

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
REM  PARA QUE NO VISUALICE LOS VALORES DE LAS VARIABLES 
SET VERIFY OFF
REM    
SET TERM ON
SET WRAP OFF

Set linesize 120
Col p1 format a120
Col p2 format a80

--listado de objetos invalidos
Spool AuxLogs\objetos_invalidos.log;
SELECT OWNER||'.'||OBJECT_NAME AS OBJECT,
  TO_CHAR(CREATED,'DD/MM/YYYY HH24:MI:SS') AS FECHA ,OBJECT_TYPE AS TIPO
FROM all_OBJECTS WHERE status='INVALID';
SPOOL OFF;
Exit;
