HOST CLS
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY OFF
SET TERM ON
SET WRAP OFF
Set linesize 120
set pagesize 0

SPOOL &2\P_07_Analaze_Ejecucion.log;

SELECT 'ANALYZE table ' || table_NAME || ' COMPUTE STATISTICS;' 
FROM user_tables
UNION ALL
SELECT 'ANALYZE INDEX ' || INDEX_NAME || ' COMPUTE STATISTICS;' 
FROM USER_INDEXES;

SPOOL OFF;

PROMPT EJECUTANDO ANALYZE;

SPOOL &2\P_07_Analaze_Ejecucion_Log.log;

SET ECHO ON

START &2\P_07_Analaze_Ejecucion.log;

SPOOL OFF;

EXIT;